package CapaVista;

import CapaLogica.ClienteCoorporativo;
import CapaLogica.ClientePersonal;
import CapaLogica.TipoUsuario;
import CapaLogica.Usuario;
import CapaLogica.Usuario_Cliente;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utilitarios.UtilitarioVentana;

public class JFrmVentanaPrincipal extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    /**
     * Constructor de la clase Creación de los componentes de Swing en el JFrame
     */
    public JFrmVentanaPrincipal() {
        initComponents();
        agregarUsuarios(); //creacion de usuarios predeterminados 
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/bmwlogo.png")).getImage());
        this.setTitle("BMW");
        agregarFondo(jLabel1, "src/imagenes/m4luz.jpg"); //para agregar el fondo 
        jMnuMantenimientos.setVisible(false);//ocultar mantenimientos
        jMnuPersonalizacion.setVisible(false);
        jMnuReportes.setVisible(false);
        jMnuFacturacion.setVisible(false);

    }

    private void agregarUsuarios() { //usuarios predeterminados
        //limpiar el admin y el vendedor (para que no se repitan los que se crean predeterminadamente)
        try {

            ArrayList<Usuario_Cliente> lista = Usuario_Cliente.listadoUsuario_Clientes();
            for (int i = 0; i < lista.size(); i++) {
                if (lista.get(i).getUsuario().getTipoUsuario().equals(TipoUsuario.ADMINISTRADOR)) {
                    Usuario_Cliente.eliminarUsuario_Cliente(lista.get(i).getUsuario().getCorreo());
                }
                if (lista.get(i).getUsuario().getTipoUsuario().equals(TipoUsuario.VENDEDOR)) {
                    Usuario_Cliente.eliminarUsuario_Cliente(lista.get(i).getUsuario().getCorreo());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JFrmVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //creacion del admin
        Usuario usuarioAdmin = new Usuario("admin", "123", "Administrador", null, "Local", "00000000", TipoUsuario.ADMINISTRADOR);
        Usuario_Cliente usuario_Cliente_Admin = new Usuario_Cliente(usuarioAdmin, "123456789");
        try {
            Usuario_Cliente.agregarUsuario_Cliente(usuario_Cliente_Admin);
        } catch (Exception ex) {
            Logger.getLogger(JFrmVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        //creacion de un vendedor
        Usuario usuarioVendedor = new Usuario("vendedor", "123", "Vendedor", null, "Local", "00000000", TipoUsuario.VENDEDOR);
        Usuario_Cliente usuario_Cliente_Vendedor = new Usuario_Cliente(usuarioVendedor, "123456789");
        try {
            Usuario_Cliente.agregarUsuario_Cliente(usuario_Cliente_Vendedor);
        } catch (Exception ex) {
            Logger.getLogger(JFrmVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // metodo para la imagen de fondo
    private void agregarFondo(JLabel nombreFondo, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(imagen.getImage().getScaledInstance(
                nombreFondo.getWidth(),
                nombreFondo.getHeight(),
                Image.SCALE_DEFAULT));
        nombreFondo.setIcon(icono);
        repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDepAdministradorEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMnuMenuPrincipal = new javax.swing.JMenuBar();
        jMnuSistema = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSalir = new javax.swing.JMenuItem();
        jMnuIngresos = new javax.swing.JMenu();
        jMenuInicioSesion = new javax.swing.JMenuItem();
        jMnuCrearCuenta = new javax.swing.JMenuItem();
        jMnuMantenimientos = new javax.swing.JMenu();
        jMenuMantenimientoClientes = new javax.swing.JMenuItem();
        jMnuMantenimientosPartesVehiculo = new javax.swing.JMenuItem();
        jMnuMantenimientoVehiculo = new javax.swing.JMenuItem();
        jMnuReportes = new javax.swing.JMenu();
        jMnuReporteClientes = new javax.swing.JMenuItem();
        jMnuReportePartesVehiculo = new javax.swing.JMenuItem();
        jMnuReporteVehiculo = new javax.swing.JMenuItem();
        jMnuReporteTotalesFacturados = new javax.swing.JMenuItem();
        jMnuPersonalizacion = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMnuPersonalizar = new javax.swing.JMenuItem();
        jMnuFacturacion = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMnuFacturar = new javax.swing.JMenuItem();
        jMnuAyuda = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnuAyudaAcercaDe = new javax.swing.JMenuItem();
        jMnuUsuario = new javax.swing.JMenu();
        jMnuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ejemplos Gráficos en Java");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDepAdministradorEscritorio.setBackground(new java.awt.Color(240, 240, 240));
        jDepAdministradorEscritorio.setForeground(new java.awt.Color(240, 240, 240));
        jDepAdministradorEscritorio.setAutoscrolls(true);

        jDepAdministradorEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDepAdministradorEscritorioLayout = new javax.swing.GroupLayout(jDepAdministradorEscritorio);
        jDepAdministradorEscritorio.setLayout(jDepAdministradorEscritorioLayout);
        jDepAdministradorEscritorioLayout.setHorizontalGroup(
            jDepAdministradorEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDepAdministradorEscritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 122, Short.MAX_VALUE))
        );
        jDepAdministradorEscritorioLayout.setVerticalGroup(
            jDepAdministradorEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDepAdministradorEscritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMnuMenuPrincipal.setBackground(new java.awt.Color(252, 108, 172));
        jMnuMenuPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jMnuMenuPrincipal.setToolTipText("");
        jMnuMenuPrincipal.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jMnuSistema.setBackground(new java.awt.Color(252, 108, 172));
        jMnuSistema.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuSistema.setForeground(new java.awt.Color(51, 51, 51));
        jMnuSistema.setText("Sistema");
        jMnuSistema.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(252, 108, 172));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jMnuSistema.add(jSeparator1);

        jMnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMnuSalir.setBackground(new java.awt.Color(252, 108, 172));
        jMnuSalir.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuSalir.setForeground(new java.awt.Color(51, 51, 51));
        jMnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        jMnuSalir.setText("Salir");
        jMnuSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSalirActionPerformed(evt);
            }
        });
        jMnuSistema.add(jMnuSalir);

        jMnuMenuPrincipal.add(jMnuSistema);

        jMnuIngresos.setBackground(new java.awt.Color(252, 108, 172));
        jMnuIngresos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuIngresos.setForeground(new java.awt.Color(51, 51, 51));
        jMnuIngresos.setText("Ingreso");
        jMnuIngresos.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jMenuInicioSesion.setBackground(new java.awt.Color(252, 108, 172));
        jMenuInicioSesion.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMenuInicioSesion.setForeground(new java.awt.Color(51, 51, 51));
        jMenuInicioSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMenuInicioSesion.setText("Iniciar sesion");
        jMenuInicioSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInicioSesionActionPerformed(evt);
            }
        });
        jMnuIngresos.add(jMenuInicioSesion);

        jMnuCrearCuenta.setBackground(new java.awt.Color(252, 108, 172));
        jMnuCrearCuenta.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuCrearCuenta.setForeground(new java.awt.Color(51, 51, 51));
        jMnuCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMnuCrearCuenta.setText("Crear Cuenta");
        jMnuCrearCuenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCrearCuentaActionPerformed(evt);
            }
        });
        jMnuIngresos.add(jMnuCrearCuenta);

        jMnuMenuPrincipal.add(jMnuIngresos);

        jMnuMantenimientos.setBackground(new java.awt.Color(252, 108, 172));
        jMnuMantenimientos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuMantenimientos.setForeground(new java.awt.Color(51, 51, 51));
        jMnuMantenimientos.setText("Mantenimientos");
        jMnuMantenimientos.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jMenuMantenimientoClientes.setBackground(new java.awt.Color(252, 108, 172));
        jMenuMantenimientoClientes.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMenuMantenimientoClientes.setForeground(new java.awt.Color(51, 51, 51));
        jMenuMantenimientoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMenuMantenimientoClientes.setText("Matenimiento Clientes");
        jMenuMantenimientoClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuMantenimientoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMantenimientoClientesActionPerformed(evt);
            }
        });
        jMnuMantenimientos.add(jMenuMantenimientoClientes);

        jMnuMantenimientosPartesVehiculo.setBackground(new java.awt.Color(252, 108, 172));
        jMnuMantenimientosPartesVehiculo.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuMantenimientosPartesVehiculo.setForeground(new java.awt.Color(51, 51, 51));
        jMnuMantenimientosPartesVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMnuMantenimientosPartesVehiculo.setText("Matenimientos Partes del Vehiculo");
        jMnuMantenimientosPartesVehiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuMantenimientosPartesVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMantenimientosPartesVehiculoActionPerformed(evt);
            }
        });
        jMnuMantenimientos.add(jMnuMantenimientosPartesVehiculo);

        jMnuMantenimientoVehiculo.setBackground(new java.awt.Color(252, 108, 172));
        jMnuMantenimientoVehiculo.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuMantenimientoVehiculo.setForeground(new java.awt.Color(51, 51, 51));
        jMnuMantenimientoVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMnuMantenimientoVehiculo.setText("Mantenimiento Vehiculos");
        jMnuMantenimientoVehiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuMantenimientoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMantenimientoVehiculoActionPerformed(evt);
            }
        });
        jMnuMantenimientos.add(jMnuMantenimientoVehiculo);

        jMnuMenuPrincipal.add(jMnuMantenimientos);

        jMnuReportes.setBackground(new java.awt.Color(252, 108, 172));
        jMnuReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuReportes.setForeground(new java.awt.Color(51, 51, 51));
        jMnuReportes.setText("Reportes");
        jMnuReportes.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jMnuReporteClientes.setBackground(new java.awt.Color(252, 108, 172));
        jMnuReporteClientes.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuReporteClientes.setForeground(new java.awt.Color(51, 51, 51));
        jMnuReporteClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMnuReporteClientes.setText("Reporte Clientes");
        jMnuReporteClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuReporteClientesActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMnuReporteClientes);

        jMnuReportePartesVehiculo.setBackground(new java.awt.Color(252, 108, 172));
        jMnuReportePartesVehiculo.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuReportePartesVehiculo.setForeground(new java.awt.Color(51, 51, 51));
        jMnuReportePartesVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMnuReportePartesVehiculo.setText("Reporte Partes del Vehiculo");
        jMnuReportePartesVehiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuReportePartesVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuReportePartesVehiculoActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMnuReportePartesVehiculo);

        jMnuReporteVehiculo.setBackground(new java.awt.Color(252, 108, 172));
        jMnuReporteVehiculo.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuReporteVehiculo.setForeground(new java.awt.Color(51, 51, 51));
        jMnuReporteVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMnuReporteVehiculo.setText("Reporte Vehiculos");
        jMnuReporteVehiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuReporteVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuReporteVehiculoActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMnuReporteVehiculo);

        jMnuReporteTotalesFacturados.setBackground(new java.awt.Color(252, 108, 172));
        jMnuReporteTotalesFacturados.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuReporteTotalesFacturados.setForeground(new java.awt.Color(51, 51, 51));
        jMnuReporteTotalesFacturados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jMnuReporteTotalesFacturados.setText("Reporte Totales Facturados");
        jMnuReporteTotalesFacturados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuReporteTotalesFacturados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuReporteTotalesFacturadosActionPerformed(evt);
            }
        });
        jMnuReportes.add(jMnuReporteTotalesFacturados);

        jMnuMenuPrincipal.add(jMnuReportes);

        jMnuPersonalizacion.setBackground(new java.awt.Color(252, 108, 172));
        jMnuPersonalizacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuPersonalizacion.setForeground(new java.awt.Color(51, 51, 51));
        jMnuPersonalizacion.setText("Personalizacion");
        jMnuPersonalizacion.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(252, 108, 172));
        jSeparator3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jMnuPersonalizacion.add(jSeparator3);

        jMnuPersonalizar.setBackground(new java.awt.Color(252, 108, 172));
        jMnuPersonalizar.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuPersonalizar.setForeground(new java.awt.Color(51, 51, 51));
        jMnuPersonalizar.setText("Personalizar");
        jMnuPersonalizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuPersonalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPersonalizarActionPerformed(evt);
            }
        });
        jMnuPersonalizacion.add(jMnuPersonalizar);

        jMnuMenuPrincipal.add(jMnuPersonalizacion);

        jMnuFacturacion.setBackground(new java.awt.Color(252, 108, 172));
        jMnuFacturacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuFacturacion.setForeground(new java.awt.Color(51, 51, 51));
        jMnuFacturacion.setText("Facturacion");
        jMnuFacturacion.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(252, 108, 172));
        jSeparator4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        jMnuFacturacion.add(jSeparator4);

        jMnuFacturar.setBackground(new java.awt.Color(252, 108, 172));
        jMnuFacturar.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuFacturar.setForeground(new java.awt.Color(51, 51, 51));
        jMnuFacturar.setText("Facturar");
        jMnuFacturar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFacturarActionPerformed(evt);
            }
        });
        jMnuFacturacion.add(jMnuFacturar);

        jMnuMenuPrincipal.add(jMnuFacturacion);

        jMnuAyuda.setBackground(new java.awt.Color(252, 108, 172));
        jMnuAyuda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuAyuda.setForeground(new java.awt.Color(51, 51, 51));
        jMnuAyuda.setText("Ayuda");
        jMnuAyuda.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(252, 108, 172));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jMnuAyuda.add(jSeparator2);

        jMnuAyudaAcercaDe.setBackground(new java.awt.Color(252, 108, 172));
        jMnuAyudaAcercaDe.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuAyudaAcercaDe.setForeground(new java.awt.Color(51, 51, 51));
        jMnuAyudaAcercaDe.setText("Acerca de...");
        jMnuAyudaAcercaDe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuAyudaAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuAyudaAcercaDeActionPerformed(evt);
            }
        });
        jMnuAyuda.add(jMnuAyudaAcercaDe);

        jMnuMenuPrincipal.add(jMnuAyuda);

        jMnuUsuario.setBackground(new java.awt.Color(252, 108, 172));
        jMnuUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jMnuUsuario.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N

        jMnuCerrarSesion.setBackground(new java.awt.Color(252, 108, 172));
        jMnuCerrarSesion.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jMnuCerrarSesion.setForeground(new java.awt.Color(51, 51, 51));
        jMnuCerrarSesion.setText("Cerrar sesion");
        jMnuCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCerrarSesionActionPerformed(evt);
            }
        });
        jMnuUsuario.add(jMnuCerrarSesion);

        jMnuMenuPrincipal.add(jMnuUsuario);

        setJMenuBar(jMnuMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDepAdministradorEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDepAdministradorEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int vResultado = 0;

        //Mostar un ConfirmDialog personalizado
        vResultado = JOptionPane.showConfirmDialog(null,
                "¿Está seguro que desea cerrar la aplicación?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION);

        //Evaluar si la respuesta del usuario fue Sí
        if (vResultado == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSalirActionPerformed
        //Esto es una forma de llamar al evento de un JFrame
        //Pasando como parámetro una nueva instancia del evento WindowEvent, con ID = 0
        formWindowClosing(new java.awt.event.WindowEvent(this, 0));
    }//GEN-LAST:event_jMnuSalirActionPerformed

    private void jMnuAyudaAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuAyudaAcercaDeActionPerformed

        JOptionPane.showMessageDialog(this,
                new JPanAcercaDe(),
                "Acerca de...",
                JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMnuAyudaAcercaDeActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        this.jDepAdministradorEscritorio.setSize(this.getSize());
    }//GEN-LAST:event_formComponentResized

    private void jMnuCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCrearCuentaActionPerformed
        jPanCrearCuenta oJPanCuenta = new jPanCrearCuenta();

        UtilitarioVentana.centrarVentanaJPanel(this, "Registrar", oJPanCuenta, jDepAdministradorEscritorio);

    }//GEN-LAST:event_jMnuCrearCuentaActionPerformed

    private void jMenuInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInicioSesionActionPerformed
        jPanInicioSesion ojPanInicioSesion = new jPanInicioSesion();
        UtilitarioVentana.centrarVentanaJPanel(this, "Iniciar Sesion", ojPanInicioSesion, jDepAdministradorEscritorio);

    }//GEN-LAST:event_jMenuInicioSesionActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        Usuario_Cliente usuario;  //es el usuario que tiene la sesion iniciada
        jPanInicioSesion jPanInicioSesion = new jPanInicioSesion();
        usuario = jPanInicioSesion.usuarioActivo();

        //Filtro de menus 
        if (usuario != null) {
            //para el inicio de sesion de un Administrador
            if (usuario.getUsuario().getTipoUsuario().equals(TipoUsuario.ADMINISTRADOR)) {
                jMnuMantenimientos.setVisible(true);
                jMnuMantenimientoVehiculo.setVisible(true);
                jMnuMantenimientosPartesVehiculo.setVisible(true);
                jMnuUsuario.setVisible(true);
                jMnuUsuario.setText("Usuario Activo: " + usuario.getUsuario().getCorreo());
                jMnuIngresos.setVisible(false);
                jMnuReportes.setVisible(true);
                jMnuFacturacion.setVisible(true);
                jMnuReporteTotalesFacturados.setVisible(true);
                jMnuReporteClientes.setVisible(true);
                jMnuReporteVehiculo.setVisible(true);
                jMnuReportePartesVehiculo.setVisible(true);
            }

            //para el inicio de sesion de un Vendedor
            if (usuario.getUsuario().getTipoUsuario().equals(TipoUsuario.VENDEDOR)) {
                jMnuMantenimientos.setVisible(true);
                jMnuMantenimientoVehiculo.setVisible(false);
                jMnuMantenimientosPartesVehiculo.setVisible(false);
                jMnuUsuario.setVisible(true);
                jMnuUsuario.setText("Usuario Activo: " + usuario.getUsuario().getCorreo());
                jMnuIngresos.setVisible(false);
                jMnuReportes.setVisible(true);
                jMnuReporteClientes.setVisible(false);
                jMnuReporteTotalesFacturados.setVisible(false);
                jMnuFacturacion.setVisible(true);
            }
            //para el inicio de sesion de un Cliente coorporativo
            if (usuario instanceof ClienteCoorporativo) {
                jMnuUsuario.setVisible(true);
                jMnuUsuario.setText("Usuario Activo: " + usuario.getUsuario().getCorreo());
                jMnuPersonalizacion.setVisible(true);
                jMnuIngresos.setVisible(false);
                jMnuReportes.setVisible(true);
                jMnuReporteClientes.setVisible(false);
                jMnuReporteTotalesFacturados.setVisible(false);
            }
            //para el inicio de sesion de un Cliente personal
            if (usuario instanceof ClientePersonal) {
                jMnuUsuario.setVisible(true);
                jMnuUsuario.setText("Usuario Activo: " + usuario.getUsuario().getCorreo());
                jMnuPersonalizacion.setVisible(true);
                jMnuIngresos.setVisible(false);
                jMnuReportes.setVisible(true);
                jMnuReporteClientes.setVisible(false);
                jMnuReporteTotalesFacturados.setVisible(false);
            }

        }
        
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void jMenuMantenimientoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMantenimientoClientesActionPerformed
        // TODO add your handling code here:
        jPanMantenimientoCliente oJPanMantenimientoCliente = new jPanMantenimientoCliente();
        UtilitarioVentana.centrarVentanaJPanel(this, "Mantenimiento Clientes", oJPanMantenimientoCliente, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMenuMantenimientoClientesActionPerformed

    private void jMnuMantenimientosPartesVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMantenimientosPartesVehiculoActionPerformed
        // TODO add your handling code here:
        jPanMantenimientoPartes ojPanMantenimientoPartes = new jPanMantenimientoPartes();
        UtilitarioVentana.centrarVentanaJPanel(this, "Mantenimiento Partes Vehiculo", ojPanMantenimientoPartes, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuMantenimientosPartesVehiculoActionPerformed

    private void jMnuMantenimientoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMantenimientoVehiculoActionPerformed
        // TODO add your handling code here:
        jPanMantenimientoVehiculo oPanMantenimientoVehiculo = new jPanMantenimientoVehiculo();
        UtilitarioVentana.centrarVentanaJPanel(this, "Mantenimiento Vehiculos", oPanMantenimientoVehiculo, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuMantenimientoVehiculoActionPerformed

    private void jMnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCerrarSesionActionPerformed
        // TODO add your handling code here:
        //vuelve a ocultar los menus como en el inicio del frame
        jMnuMantenimientos.setVisible(false);
        jMnuReportes.setVisible(false);
        jMnuUsuario.setVisible(false);
        jMnuPersonalizacion.setVisible(false);
        jMnuIngresos.setVisible(true);
        jMnuFacturacion.setVisible(false);

    }//GEN-LAST:event_jMnuCerrarSesionActionPerformed

    private void jMnuPersonalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPersonalizarActionPerformed
        // TODO add your handling code here:
        jPanPersonalizacion panPersonalizacion = new jPanPersonalizacion();
        UtilitarioVentana.centrarVentanaJPanel(this, "Personalizacion", panPersonalizacion, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuPersonalizarActionPerformed

    private void jMnuReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuReporteClientesActionPerformed
        // TODO add your handling code here:
        jPanReporteCliente jPanReporteCliente1 = new jPanReporteCliente();
        UtilitarioVentana.centrarVentanaJPanel(this, "Reporte Clientes", jPanReporteCliente1, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuReporteClientesActionPerformed

    private void jMnuReportePartesVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuReportePartesVehiculoActionPerformed
        // TODO add your handling code here:
        jPanReportePartes panReportePartes = new jPanReportePartes();
        UtilitarioVentana.centrarVentanaJPanel(this, "Reporte Partes Del Vehiculo", panReportePartes, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuReportePartesVehiculoActionPerformed

    private void jMnuReporteVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuReporteVehiculoActionPerformed
        // TODO add your handling code here:
        jPanReporteVehiculo panReporteVehiculo = new jPanReporteVehiculo();
        UtilitarioVentana.centrarVentanaJPanel(this, "Reporte Vehiculos", panReporteVehiculo, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuReporteVehiculoActionPerformed

    private void jMnuReporteTotalesFacturadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuReporteTotalesFacturadosActionPerformed
        // TODO add your handling code here:
        jPanReporteFacturas ojPanReporteFacturas = new jPanReporteFacturas();
        UtilitarioVentana.centrarVentanaJPanel(this, "Reporte Facturas", ojPanReporteFacturas, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuReporteTotalesFacturadosActionPerformed

    private void jMnuFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFacturarActionPerformed
        // TODO add your handling code here:
        jPanFacturacion ojPanFacturacion = new jPanFacturacion();
        UtilitarioVentana.centrarVentanaJPanel(this, "Facturacion", ojPanFacturacion, jDepAdministradorEscritorio);
    }//GEN-LAST:event_jMnuFacturarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDepAdministradorEscritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuInicioSesion;
    private javax.swing.JMenuItem jMenuMantenimientoClientes;
    private javax.swing.JMenu jMnuAyuda;
    private javax.swing.JMenuItem jMnuAyudaAcercaDe;
    private javax.swing.JMenuItem jMnuCerrarSesion;
    private javax.swing.JMenuItem jMnuCrearCuenta;
    private javax.swing.JMenu jMnuFacturacion;
    private javax.swing.JMenuItem jMnuFacturar;
    private javax.swing.JMenu jMnuIngresos;
    private javax.swing.JMenuItem jMnuMantenimientoVehiculo;
    private javax.swing.JMenu jMnuMantenimientos;
    private javax.swing.JMenuItem jMnuMantenimientosPartesVehiculo;
    private javax.swing.JMenuBar jMnuMenuPrincipal;
    private javax.swing.JMenu jMnuPersonalizacion;
    private javax.swing.JMenuItem jMnuPersonalizar;
    private javax.swing.JMenuItem jMnuReporteClientes;
    private javax.swing.JMenuItem jMnuReportePartesVehiculo;
    private javax.swing.JMenuItem jMnuReporteTotalesFacturados;
    private javax.swing.JMenuItem jMnuReporteVehiculo;
    private javax.swing.JMenu jMnuReportes;
    private javax.swing.JMenuItem jMnuSalir;
    private javax.swing.JMenu jMnuSistema;
    private javax.swing.JMenu jMnuUsuario;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables

}
