/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CapaVista;

import CapaLogica.Usuario_Cliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilitarios.UtilitarioVentana;

public class jPanInicioSesion extends javax.swing.JPanel {

    static int cont = 0;
    static String usuarioCorreo = "";
    static String contrasena = "";

    /**
     * Creates new form jPanInicioSesion
     */
    public jPanInicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPassContrasena = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jBtnIngresar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Iniciar Sesion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("8-bit Operator+", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        setPreferredSize(new java.awt.Dimension(551, 349));

        jLabel1.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioIcon.png"))); // NOI18N
        jLabel1.setText("  Correo");

        jLabel2.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PasswordIcon.png"))); // NOI18N
        jLabel2.setText("Contraseña");

        jPassContrasena.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jPassContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassContrasenaActionPerformed(evt);
            }
        });
        jPassContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassContrasenaKeyTyped(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        jBtnIngresar.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jBtnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnIngresar.setText("  Ingresar");
        jBtnIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarActionPerformed(evt);
            }
        });

        jBtnSalir.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        jBtnSalir.setText("  Salir");
        jBtnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jBtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIngresar)
                    .addComponent(jBtnSalir))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //este es el usuario que se guarda luego de ingresar (El que está activo)
    public Usuario_Cliente usuarioActivo() {
        Usuario_Cliente usuario = null;
        try {
            usuario = Usuario_Cliente.consultarUsuario_Cliente(usuarioCorreo, contrasena);
        } catch (Exception ex) {
            Logger.getLogger(jPanInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return usuario;
    }


    private void jPassContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassContrasenaActionPerformed
        jBtnIngresar.doClick();
    }//GEN-LAST:event_jPassContrasenaActionPerformed

    private void jPassContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassContrasenaKeyTyped
        //tope de 12 caracteres en la contrasena
        if (jPassContrasena.getText().length() >= 12) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jPassContrasenaKeyTyped

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed

        jPassContrasena.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped

    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void jBtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarActionPerformed
        usuarioCorreo = txtUsuario.getText();
        contrasena = jPassContrasena.getText();
        Usuario_Cliente usuarioSesion = null;
        try {
            usuarioSesion = Usuario_Cliente.consultarUsuario_Cliente(usuarioCorreo, contrasena);
        } catch (Exception ex) {
            Logger.getLogger(jPanInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (Usuario_Cliente.consultarUsuario_ClienteBoolean(usuarioCorreo, contrasena)) { //inicio de sesion
                JOptionPane.showMessageDialog(this, "Inicio de sesion exitoso");
                usuarioActivo(); //aqui se guarda el usuario activo
            } else {// error de ingreso
                cont++;
                JOptionPane.showMessageDialog(this, "Error, su usuario y contraseña no coinsiden con ninguna cuenta existente");
                getToolkit().beep();

                if (cont == 3) {
                    JOptionPane.showMessageDialog(this, "Limite de intentos superado");
                    System.exit(0);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(jPanInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        UtilitarioVentana.cerrarPanel(this);
        JFrmVentanaPrincipal jFrmVentanaPrincipal = new JFrmVentanaPrincipal();
        jFrmVentanaPrincipal.requestFocus();


    }//GEN-LAST:event_jBtnIngresarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        UtilitarioVentana.cerrarPanel(this);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    public static String getUsuarioCorreo() {
        return usuarioCorreo;
    }

    public static void setUsuarioCorreo(String usuarioCorreo) {
        jPanInicioSesion.usuarioCorreo = usuarioCorreo;
    }

    public static String getContrasena() {
        return contrasena;
    }

    public static void setContrasena(String contrasena) {
        jPanInicioSesion.contrasena = contrasena;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIngresar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
