package CapaVista;

import CapaLogica.ETipoMoneda;
import CapaVista.*;
import CapaLogica.ETipoVehiculo;
import CapaLogica.Estado;
import CapaLogica.Partes;
import CapaLogica.Vehiculo;
import CapaVista.*;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.UtilitarioVentana;
import utilitarios.UtilitarioVentana;
import utilitarios.ValidadorFormatos;
import utilitarios.ValidadorFormatos;

public class jPanPersonalizacion extends javax.swing.JPanel {

    static Vehiculo vehiculoSeleccionado;
    static Partes parteSeleccionada;
    static ArrayList<Partes> listaPartesSeleccionadas = new ArrayList<>();

    private static double precio;

    private ETipoVehiculo tipoVehiculoC = null;

    /**
     * Creates new form jPanAdministrador
     */
    public jPanPersonalizacion() {
        initComponents();
        llenarComboVehiculos();
        llenarComboPartesExtras();

    }

    public void llenarComboPartesExtras() {
        jCboPartesExtra.removeAllItems();
        try {
            ArrayList<Partes> listaPartes = Partes.listadoPartes();
            for (Partes partes : listaPartes) {
                jCboPartesExtra.addItem(partes);
            }
            jCboPartesExtra.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(jPanPersonalizacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void llenarComboVehiculos() {
        jCboVehiculos.removeAllItems();
        try {
            ArrayList<Vehiculo> listaVehiculos = Vehiculo.listadoVehiculo();
            for (Vehiculo vehiculo : listaVehiculos) {
                jCboVehiculos.addItem(vehiculo);
            }
            jCboVehiculos.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(jPanPersonalizacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void llenarComboVehiculosFiltro() {
        jCboVehiculos.removeAllItems();
        if (jCheckFosil.isSelected()) {
            tipoVehiculoC = ETipoVehiculo.FOSIL;
        }
        if (jCheckHibrido.isSelected()) {
            tipoVehiculoC = ETipoVehiculo.HIBRIDO;
        }
        if (jCheckElectrico.isSelected()) {
            tipoVehiculoC = ETipoVehiculo.ELECTRICO;
        }
        try {
            ArrayList<Vehiculo> listaVehiculos = Vehiculo.listadoVehiculo();
            for (Vehiculo vehiculo : listaVehiculos) {
                if (vehiculo.geteTipoVehiculo().equals(tipoVehiculoC)) {
                    jCboVehiculos.addItem(vehiculo);
                }
            }
            jCboVehiculos.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(jPanPersonalizacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    

    public void limpiarCampos() {

        txtPrecio.setText("");
        buttonGroup1.clearSelection();
    }

    public static double calculaPrecio(){
        precio=0;
        precio=vehiculoSeleccionado.getPrecio();
        for (Partes partes : listaPartesSeleccionadas) {
            precio+=partes.getPrecio();
        }
        return precio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtPrecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckFosil = new javax.swing.JCheckBox();
        jCheckElectrico = new javax.swing.JCheckBox();
        jCheckHibrido = new javax.swing.JCheckBox();
        jCheckTodos = new javax.swing.JCheckBox();
        jCboVehiculos = new javax.swing.JComboBox<>();
        jBtnAgregarVehiculo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCboPartesExtra = new javax.swing.JComboBox<>();
        jBtnAgregarParte = new javax.swing.JButton();
        jBtnLimpiarSelecciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaVAgregados = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxaPAgregados = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecio.setEditable(false);
        txtPrecio.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 410, 330, 30));

        jLabel2.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio.png"))); // NOI18N
        jLabel2.setText("Precio");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, 193, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro.png"))); // NOI18N
        jLabel8.setText("Seleccione El Vehiculo Que Desea");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar El Tipo De Vehiculo Deseado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("8-bit Operator+", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        buttonGroup1.add(jCheckFosil);
        jCheckFosil.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckFosil.setText("Fosil");
        jCheckFosil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckFosil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckFosilActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckElectrico);
        jCheckElectrico.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckElectrico.setText("Electrico");
        jCheckElectrico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckElectricoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckHibrido);
        jCheckHibrido.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckHibrido.setText("Hibrido");
        jCheckHibrido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckHibrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckHibridoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckTodos);
        jCheckTodos.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckTodos.setText("Todos");
        jCheckTodos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckHibrido)
                    .addComponent(jCheckTodos)
                    .addComponent(jCheckFosil)
                    .addComponent(jCheckElectrico))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckFosil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckElectrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckHibrido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckTodos)
                .addGap(16, 16, 16))
        );

        jCboVehiculos.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCboVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVehiculosActionPerformed(evt);
            }
        });

        jBtnAgregarVehiculo.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnAgregarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnAgregarVehiculo.setText("Agregar");
        jBtnAgregarVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAgregarVehiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgregarVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mechanicwrench_118392.png"))); // NOI18N
        jLabel3.setText("Partes Extras Disponibles");

        jCboPartesExtra.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCboPartesExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboPartesExtraActionPerformed(evt);
            }
        });

        jBtnAgregarParte.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnAgregarParte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnAgregarParte.setText("Agregar");
        jBtnAgregarParte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAgregarParte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarParteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregarParte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboPartesExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jCboPartesExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgregarParte)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 810, 210));

        jBtnLimpiarSelecciones.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnLimpiarSelecciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basurero.png"))); // NOI18N
        jBtnLimpiarSelecciones.setText("Limpiar selecciones");
        jBtnLimpiarSelecciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLimpiarSelecciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLimpiarSelecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarSeleccionesActionPerformed(evt);
            }
        });
        add(jBtnLimpiarSelecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 300, 200, -1));

        jTxaVAgregados.setColumns(20);
        jTxaVAgregados.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jTxaVAgregados.setRows(5);
        jScrollPane1.setViewportView(jTxaVAgregados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 600, 70));

        jLabel4.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mechanicwrench_118392.png"))); // NOI18N
        jLabel4.setText("Partes Agregadas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 290, -1));

        jTxaPAgregados.setColumns(20);
        jTxaPAgregados.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jTxaPAgregados.setRows(5);
        jScrollPane2.setViewportView(jTxaPAgregados);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 600, 120));

        jLabel9.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro.png"))); // NOI18N
        jLabel9.setText("Vehiculos Agregado");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 320, -1));

        jBtnSalir.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        jBtnSalir.setText("Cancelar");
        jBtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 470, 130, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarVehiculoActionPerformed
        // TODO add your handling code here:

        Vehiculo vehiculo;
        if (jCboVehiculos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el Vehiculo primero");
            getToolkit().beep();
            return;
        }
        vehiculoSeleccionado = (Vehiculo) jCboVehiculos.getSelectedItem();
        jTxaVAgregados.append(vehiculoSeleccionado.toString());
        txtPrecio.setText(String.valueOf(calculaPrecio()));
    }//GEN-LAST:event_jBtnAgregarVehiculoActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jCheckHibridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckHibridoActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculosFiltro();
    }//GEN-LAST:event_jCheckHibridoActionPerformed

    private void jCheckElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckElectricoActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculosFiltro();
    }//GEN-LAST:event_jCheckElectricoActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped

    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jCboPartesExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboPartesExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboPartesExtraActionPerformed

    private void jBtnAgregarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarParteActionPerformed
        // TODO add your handling code here:
        if (jCboVehiculos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe Agregar el Vehiculo primero");
            getToolkit().beep();
            return;
        }
        if (jCboPartesExtra.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la parte primero");
            getToolkit().beep();
            return;
        }
        parteSeleccionada = (Partes) jCboPartesExtra.getSelectedItem();
        listaPartesSeleccionadas.add(parteSeleccionada);
        jTxaPAgregados.setText("");
        for (Partes partes : listaPartesSeleccionadas) {
            jTxaPAgregados.append("\n" + partes.toString());
            
        }
        txtPrecio.setText(String.valueOf(calculaPrecio()));
    }//GEN-LAST:event_jBtnAgregarParteActionPerformed

    private void jCheckTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTodosActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculos();
    }//GEN-LAST:event_jCheckTodosActionPerformed

    private void jCheckFosilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckFosilActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculosFiltro();
    }//GEN-LAST:event_jCheckFosilActionPerformed

    private void jCboVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVehiculosActionPerformed

    private void jBtnLimpiarSeleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarSeleccionesActionPerformed
        // TODO add your handling code here:
        vehiculoSeleccionado = null;
        parteSeleccionada = null;
        jTxaPAgregados.setText("");
        jTxaVAgregados.setText("");
        buttonGroup1.clearSelection();
        jCboPartesExtra.setSelectedIndex(-1);
        jCboVehiculos.setSelectedIndex(-1);
        listaPartesSeleccionadas = new ArrayList<>();
        precio =0;
        txtPrecio.setText("");
    }//GEN-LAST:event_jBtnLimpiarSeleccionesActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        UtilitarioVentana.cerrarPanel(this);

    }//GEN-LAST:event_jBtnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnAgregarParte;
    private javax.swing.JButton jBtnAgregarVehiculo;
    private javax.swing.JButton jBtnLimpiarSelecciones;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<Partes> jCboPartesExtra;
    private javax.swing.JComboBox<Vehiculo> jCboVehiculos;
    private javax.swing.JCheckBox jCheckElectrico;
    private javax.swing.JCheckBox jCheckFosil;
    private javax.swing.JCheckBox jCheckHibrido;
    private javax.swing.JCheckBox jCheckTodos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxaPAgregados;
    private javax.swing.JTextArea jTxaVAgregados;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
