package CapaVista;

import CapaVista.*;
import CapaVista.*;
import CapaLogica.Estado;
import CapaLogica.Partes;
import CapaVista.*;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.UtilitarioVentana;
import utilitarios.UtilitarioVentana;
import utilitarios.ValidadorFormatos;
import utilitarios.ValidadorFormatos;

public class jPanReportePartes extends javax.swing.JPanel {

    private MiModeloTabla dtmModeloTable = new MiModeloTabla(
            new String[]{"Codigo", "Descripcion", "Estado", "Precio"}, 0);         

    /**
     * Creates new form jPanAdministrador
     */
    public jPanReportePartes() {
        initComponents();
        llenarTablaPartes();
        jTablePartes.setModel(dtmModeloTable);
        llenarComboEstado();
    }

    public void limpiarCampos() {
       
        
    }

    public void llenarComboEstado() {
        
    }

    private void llenarTablaPartes() {
        try {
            //Llama al método que llena la lista con los  del ArrayList
            //Llena la tabla con los  que se grabaron en el ArrayList
            dtmModeloTable.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[4];
            //Obtiene el arrayList con la lista de los  que están en el archivo
            ArrayList<Partes> lista = Partes.listadoPartes();
            for (int i = 0; i < lista.size(); i++) {

                datos[0] = lista.get(i).getCodigo();
                datos[1] = lista.get(i).getDescripcion();
                datos[2] = lista.get(i).getEstado();
                datos[3] = lista.get(i).getPrecio();

                dtmModeloTable.addRow(datos);

                jTablePartes.setModel(dtmModeloTable);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla de Partes\n"
                    + "el programa se cerrará consulte con el administrador\n"
                    + e.toString());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePartes = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator1);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTablePartes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Estado", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePartes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePartesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePartes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1330, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        UtilitarioVentana.cerrarPanel(this);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jTablePartesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePartesMouseClicked
       

    }//GEN-LAST:event_jTablePartesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTablePartes;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
