package CapaVista;

import CapaVista.*;
import CapaLogica.ETipoVehiculo;
import CapaLogica.Partes;
import CapaLogica.Vehiculo;
import CapaVista.*;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.UtilitarioVentana;
import utilitarios.UtilitarioVentana;
import utilitarios.ValidadorFormatos;
import utilitarios.ValidadorFormatos;

public class jPanReporteVehiculo extends javax.swing.JPanel {

    private MiModeloTabla dtmModeloTable = new MiModeloTabla(
            new String[]{"Codigo", "Modelo", "Tipo de Vehiculo", "Precio"}, 0);    
   
    private ETipoVehiculo tipoVehiculo;

    /**
     * Creates new form jPanAdministrador
     */
    public jPanReporteVehiculo() {
        initComponents();
        llenarTablaVehiculos();
        jTableVehiculos.setModel(dtmModeloTable);
    }

    public void limpiarCampos() {
        buttonGroup1.clearSelection();
    }

    

    private void llenarTablaVehiculos() {
        try {
            //Llama al método que llena la lista con los  del ArrayList
            //Llena la tabla con los  que se grabaron en el ArrayList
            
            dtmModeloTable.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[4];
            //Obtiene el arrayList con la lista de los  que están en el archivo
            ArrayList<Vehiculo> lista = Vehiculo.listadoVehiculo();
            for (int i = 0; i < lista.size(); i++) {
                datos[0] = lista.get(i).getCodigoAuto();
                datos[1] = lista.get(i).getModelo();
                datos[2] = lista.get(i).geteTipoVehiculo();
                datos[3] = lista.get(i).getPrecio();

                dtmModeloTable.addRow(datos);
            
                jTableVehiculos.setModel(dtmModeloTable);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla de Vehiculos\n"
                    + "el programa se cerrará consulte con el administrador\n"
                    + e.toString());
        }
    }

    //filtros
    private void llenarTablaVehiculosJCheck() {
        try {
            //Llama al método que llena la lista con los  del ArrayList
            //Llena la tabla con los  que se grabaron en el ArrayList
            if(jChkFosil.isSelected()){
                tipoVehiculo = ETipoVehiculo.FOSIL;
            }
            if(jChkHibrido.isSelected()){
                tipoVehiculo = ETipoVehiculo.HIBRIDO;
            }
            if(jChkElectrico.isSelected()){
                tipoVehiculo = ETipoVehiculo.ELECTRICO;
            }
            dtmModeloTable.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[4];
            //Obtiene el arrayList con la lista de los  que están en el archivo
            ArrayList<Vehiculo> lista = Vehiculo.listadoVehiculo();
            for (int i = 0; i < lista.size(); i++) {
             if(lista.get(i).geteTipoVehiculo().equals(tipoVehiculo)){   
                datos[0] = lista.get(i).getCodigoAuto();
                datos[1] = lista.get(i).getModelo();
                datos[2] = lista.get(i).geteTipoVehiculo();
                datos[3] = lista.get(i).getPrecio();

                dtmModeloTable.addRow(datos);
            }
                jTableVehiculos.setModel(dtmModeloTable);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla de Vehiculos\n"
                    + "el programa se cerrará consulte con el administrador\n"
                    + e.toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jChkFosil = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jChkHibrido = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jChkElectrico = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnRetroceder = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehiculos = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator3);

        buttonGroup1.add(jChkFosil);
        jChkFosil.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jChkFosil.setText("Fosil");
        jChkFosil.setFocusable(false);
        jChkFosil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jChkFosil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jChkFosil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkFosilActionPerformed(evt);
            }
        });
        jToolBar1.add(jChkFosil);
        jToolBar1.add(jSeparator2);

        buttonGroup1.add(jChkHibrido);
        jChkHibrido.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jChkHibrido.setText("Hibrido");
        jChkHibrido.setFocusable(false);
        jChkHibrido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jChkHibrido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jChkHibrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkHibridoActionPerformed(evt);
            }
        });
        jToolBar1.add(jChkHibrido);
        jToolBar1.add(jSeparator4);

        buttonGroup1.add(jChkElectrico);
        jChkElectrico.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jChkElectrico.setText("Electrico");
        jChkElectrico.setFocusable(false);
        jChkElectrico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jChkElectrico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jChkElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkElectricoActionPerformed(evt);
            }
        });
        jToolBar1.add(jChkElectrico);
        jToolBar1.add(jSeparator5);

        btnRetroceder.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/retroceder.png"))); // NOI18N
        btnRetroceder.setText("Retroceder Filtro");
        btnRetroceder.setFocusable(false);
        btnRetroceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetroceder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRetroceder);
        jToolBar1.add(jSeparator1);

        btnSalir.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Modelo", "Tipo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVehiculos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1440, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        UtilitarioVentana.cerrarPanel(this);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jTableVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVehiculosMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTableVehiculosMouseClicked

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        llenarTablaVehiculos();
        limpiarCampos();
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void jChkFosilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkFosilActionPerformed
        // TODO add your handling code here:
        llenarTablaVehiculosJCheck();
    }//GEN-LAST:event_jChkFosilActionPerformed

    private void jChkHibridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkHibridoActionPerformed
        // TODO add your handling code here:
        llenarTablaVehiculosJCheck();
    }//GEN-LAST:event_jChkHibridoActionPerformed

    private void jChkElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkElectricoActionPerformed
        // TODO add your handling code here:
        llenarTablaVehiculosJCheck();
    }//GEN-LAST:event_jChkElectricoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jChkElectrico;
    private javax.swing.JCheckBox jChkFosil;
    private javax.swing.JCheckBox jChkHibrido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTable jTableVehiculos;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
