package CapaVista;

import CapaVista.*;
import CapaLogica.Estado;
import CapaLogica.Partes;
import CapaVista.*;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.UtilitarioVentana;
import utilitarios.UtilitarioVentana;
import utilitarios.ValidadorFormatos;
import utilitarios.ValidadorFormatos;

public class jPanMantenimientoPartes extends javax.swing.JPanel {

    private MiModeloTabla dtmModeloTable = new MiModeloTabla(
            new String[]{"Codigo", "Descripcion", "Estado", "Precio"}, 0);

    /**
     * Creates new form jPanAdministrador
     */
    public jPanMantenimientoPartes() {
        initComponents();
        llenarTablaPartes();
        jTablePartes.setModel(dtmModeloTable);
        llenarComboEstado();
    }

    public void limpiarCampos() {
        txtCodigo.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        jCboEstado.setSelectedIndex(-1);

    }

    public void llenarComboEstado() {
        jCboEstado.removeAllItems();
        for (Estado estado : Estado.values()) {
            jCboEstado.addItem(estado);
        }
        jCboEstado.setSelectedIndex(-1);
    }

    private void llenarTablaPartes() {
        try {
            //Llama al método que llena la lista con los  del ArrayList
            //Llena la tabla con los  que se grabaron en el ArrayList
            dtmModeloTable.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[4];
            //Obtiene el arrayList con la lista de los  que están en el archivo
            ArrayList<Partes> lista = Partes.listadoPartes();
            for (int i = 0; i < lista.size(); i++) {

                datos[0] = lista.get(i).getCodigo();
                datos[1] = lista.get(i).getDescripcion();
                datos[2] = lista.get(i).getEstado();
                datos[3] = lista.get(i).getPrecio();

                dtmModeloTable.addRow(datos);

                jTablePartes.setModel(dtmModeloTable);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla de Partes\n"
                    + "el programa se cerrará consulte con el administrador\n"
                    + e.toString());
        }
    }

    private void llenarTablaPartesValoresAproximados() {

        if (ValidadorFormatos.validarVacio(txtCodigo.getText()) && ValidadorFormatos.validarVacio(txtDescripcion.getText())
                && ValidadorFormatos.validarVacio(String.valueOf(txtPrecio.getText()))) {
            JOptionPane.showMessageDialog(this, "Debe digitar como minimo su Codigo, Descripcion, Precio");
            txtCodigo.requestFocus();
            getToolkit().beep();
            return;
        }

        try {
            //Llama al método que llena la lista con los  del ArrayList
            //Llena la tabla con los  que se grabaron en el ArrayList
            dtmModeloTable.setRowCount(0);//Limpia la tabla
            Object[] datos = new Object[4];
            //Obtiene el arrayList con la lista de los  que están en el archivo
            ArrayList<Partes> lista = Partes.listadoPartes();
            for (int i = 0; i < lista.size(); i++) {
                if (lista.get(i).getDescripcion().equals(txtDescripcion.getText()) || lista.get(i).getCodigo().equalsIgnoreCase(txtCodigo.getText())) {
                    datos[0] = lista.get(i).getCodigo();
                    datos[1] = lista.get(i).getDescripcion();
                    datos[2] = lista.get(i).getEstado();
                    datos[3] = lista.get(i).getPrecio();

                    dtmModeloTable.addRow(datos);

                }
                jTablePartes.setModel(dtmModeloTable);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al llenar la tabla de Vehiculos\n"
                    + "el programa se cerrará consulte con el administrador\n"
                    + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnAceptar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePartes = new javax.swing.JTable();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCboEstado = new javax.swing.JComboBox<>();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        btnAceptar.setText("Agregar");
        btnAceptar.setFocusable(false);
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAceptar);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editor.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basurero.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarLupa.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setFocusable(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultar);

        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/retroceder.png"))); // NOI18N
        btnRetroceder.setText("Retroceder Consulta");
        btnRetroceder.setFocusable(false);
        btnRetroceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetroceder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRetroceder);
        jToolBar1.add(jSeparator1);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jTablePartes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Estado", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePartes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePartesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePartes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 370, 1330, 370));

        txtPrecio.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 330, 30));

        jLabel8.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mechanicwrench_118392.png"))); // NOI18N
        jLabel8.setText("Descripcion");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, -1));

        txtDescripcion.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 330, 30));

        jLabel1.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/codigo.png"))); // NOI18N
        jLabel1.setText("Codigo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 94, -1));

        txtCodigo.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 330, 30));

        jLabel2.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio.png"))); // NOI18N
        jLabel2.setText("Precio");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 193, 30));

        jLabel3.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mechanicwrench_118392.png"))); // NOI18N
        jLabel3.setText("Estado");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 193, 30));

        jCboEstado.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        add(jCboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 330, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        // valida que el campo de texto del nombre no este vacio
        if (ValidadorFormatos.validarVacio(txtCodigo.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar el codigo");
            txtCodigo.requestFocus();
            return;
        }
        
        try {
            ArrayList<Partes> lista = Partes.listadoPartes();
            for (Partes partes : lista) {
                if (txtCodigo.getText().equalsIgnoreCase(partes.getCodigo())) {
                    JOptionPane.showMessageDialog(this, "Este Codigo ya existe");
                    return;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(jPanMantenimientoPartes.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (ValidadorFormatos.validarVacio(txtDescripcion.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar la descripcion");
            txtDescripcion.requestFocus();
            return;
        }

        // validar que sean letras 
        // valida que el campo del correo electronico no este vacio
        if (ValidadorFormatos.validarVacio(txtPrecio.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar el precio");
            txtPrecio.requestFocus();
            return;
        }

        if (jCboEstado.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el estado");
            jCboEstado.requestFocus();
            return;
        }

        //creacion de la parte
        Estado estado = (Estado) jCboEstado.getSelectedItem();
        Partes partes = new Partes(txtCodigo.getText(), txtDescripcion.getText(), estado, Double.parseDouble(txtPrecio.getText()));
        if (partes != null) { //Revisa si el JDialog construyó el nuevo 
            try {
                Partes.agregarParte(partes);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al guardar la parte\n"
                        + "el programa se cerrará consulte con el administrador\n"
                        + e.toString());
                // e.printStackTrace();//Muestra la caída
                System.exit(0);
            }
            //actualiza la tabla de manera que se vea el nuevo 
            llenarTablaPartes();
            limpiarCampos();

        }

        limpiarCampos();

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        // valida que el campo de texto del nombre no este vacio
        if (ValidadorFormatos.validarVacio(txtCodigo.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar el codigo");
            txtCodigo.requestFocus();
            return;
        }

        

        if (ValidadorFormatos.validarVacio(txtDescripcion.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar el modelo");
            txtDescripcion.requestFocus();
            return;
        }

        // validar que sean letras 
        // valida que el campo del correo electronico no este vacio
        if (ValidadorFormatos.validarVacio(txtPrecio.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar el precio");
            txtPrecio.requestFocus();
            return;
        }

        if (jCboEstado.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el estado");
            jCboEstado.requestFocus();
            return;
        }

        //creacion de la parte
        //creacion de la parte
        Estado estado = (Estado) jCboEstado.getSelectedItem();
        Partes partes = new Partes(txtCodigo.getText(), txtDescripcion.getText(), estado, Double.parseDouble(txtPrecio.getText()));
        if (partes != null) { //Revisa si el JDialog construyó el nuevo 
            try {
                Partes.modificarParte(partes);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al guardar la parte\n"
                        + "el programa se cerrará consulte con el administrador\n"
                        + e.toString());
                // e.printStackTrace();//Muestra la caída
                System.exit(0);
            }
            //actualiza la tabla de manera que se vea el nuevo 
            llenarTablaPartes();
            limpiarCampos();

        }

        limpiarCampos();

//        Estado estado = (Estado)jCboEstado.getSelectedItem();
//        Partes partes = new Partes(txtCodigo.getText(), txtDescripcion.getText(), estado, Double.parseDouble(txtPrecio.getSelectedText()));
//        if (partes != null) { //Revisa si el JDialog construyó el nuevo 
//            try {
//                Partes.modificarParte(partes);
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Error al guardar la parte\n"
//                        + "el programa se cerrará consulte con el administrador\n"
//                        + e.toString());
//                // e.printStackTrace();//Muestra la caída
//                System.exit(0);
//            }
//            //actualiza la tabla de manera que se vea el nuevo 
//            llenarTablaPartes(); 
//            
//            limpiarCampos();
//
//        }
//
//        limpiarCampos();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (jTablePartes.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la parte a eliminar");
            return;
        }

        String codigo = jTablePartes.getValueAt(jTablePartes.getSelectedRow(), 0).toString();

        try {
            Partes.eliminarParte(codigo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar el vehiculo\n"
                    + "el programa se cerrará consulte con el administrador\n"
                    + e.toString());
            System.exit(0);
        }
        llenarTablaPartes(); //actualiza la tabla con el nuevo   

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        llenarTablaPartesValoresAproximados();

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        UtilitarioVentana.cerrarPanel(this);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped

    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
        txtPrecio.requestFocus();
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        txtDescripcion.requestFocus();
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        //validar que el usuario este digitando solo letras

    }//GEN-LAST:event_txtCodigoKeyTyped

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jTablePartesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePartesMouseClicked
        // TODO add your handling code here:
        String codigo = jTablePartes.getValueAt(jTablePartes.getSelectedRow(), 0).toString();
        txtCodigo.setText(codigo);
        String modelo = jTablePartes.getValueAt(jTablePartes.getSelectedRow(), 1).toString();
        txtDescripcion.setText(modelo);

        String precio = jTablePartes.getValueAt(jTablePartes.getSelectedRow(), 3).toString();
        txtPrecio.setText(precio);

        txtCodigo.requestFocus();

    }//GEN-LAST:event_jTablePartesMouseClicked

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        llenarTablaPartes();
    }//GEN-LAST:event_btnRetrocederActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Estado> jCboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTablePartes;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
