package CapaVista;

import CapaLogica.ClienteCoorporativo;
import CapaLogica.ClientePersonal;
import CapaVista.*;
import CapaLogica.ETipoMoneda;
import CapaVista.*;
import CapaLogica.ETipoVehiculo;
import CapaLogica.Estado;
import CapaLogica.Factura;
import CapaLogica.Partes;
import CapaLogica.Usuario_Cliente;
import CapaLogica.Vehiculo;
import CapaVista.*;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.UtilitarioVentana;
import utilitarios.UtilitarioVentana;
import utilitarios.ValidadorFormatos;
import utilitarios.ValidadorFormatos;

public class jPanFacturacion extends javax.swing.JPanel {

    static Vehiculo vehiculoSeleccionado;
    static Partes parteSeleccionada;
    static ArrayList<Partes> listaPartesSeleccionadas = new ArrayList<>();
    static Usuario_Cliente usuario_Cliente;
    static Factura factura;
    static int numeroFacturaA =0;
    private ETipoVehiculo tipoVehiculoC = null;

    /**
     * Creates new form jPanAdministrador
     */
    public jPanFacturacion() {
        initComponents();
        llenarComboVehiculos();
        llenarComboPartesExtras();

    }

    public void llenarComboPartesExtras() {
        jCboPartesExtra.removeAllItems();
        try {
            ArrayList<Partes> listaPartes = Partes.listadoPartes();
            for (Partes partes : listaPartes) {
                jCboPartesExtra.addItem(partes);
            }
            jCboPartesExtra.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(jPanFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void llenarComboVehiculos() {
        jCboVehiculos.removeAllItems();
        try {
            ArrayList<Vehiculo> listaVehiculos = Vehiculo.listadoVehiculo();
            for (Vehiculo vehiculo : listaVehiculos) {
                jCboVehiculos.addItem(vehiculo);
            }
            jCboVehiculos.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(jPanFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void llenarComboVehiculosFiltro() {
        jCboVehiculos.removeAllItems();
        if (jCheckFosil.isSelected()) {
            tipoVehiculoC = ETipoVehiculo.FOSIL;
        }
        if (jCheckHibrido.isSelected()) {
            tipoVehiculoC = ETipoVehiculo.HIBRIDO;
        }
        if (jCheckElectrico.isSelected()) {
            tipoVehiculoC = ETipoVehiculo.ELECTRICO;
        }
        try {
            ArrayList<Vehiculo> listaVehiculos = Vehiculo.listadoVehiculo();
            for (Vehiculo vehiculo : listaVehiculos) {
                if (vehiculo.geteTipoVehiculo().equals(tipoVehiculoC)) {
                    jCboVehiculos.addItem(vehiculo);
                }
            }
            jCboVehiculos.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(jPanFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static double calculaSubTotal() {
        double precio = 0;
        precio = vehiculoSeleccionado.getPrecio();
        for (Partes partes : listaPartesSeleccionadas) {
            precio += partes.getPrecio();
        }
        return precio;
    }

    public void limpiarCampos() {

        txtCedulaCliente.setText("");
        buttonGroup1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckFosil = new javax.swing.JCheckBox();
        jCheckElectrico = new javax.swing.JCheckBox();
        jCheckHibrido = new javax.swing.JCheckBox();
        jCheckTodos = new javax.swing.JCheckBox();
        jCboVehiculos = new javax.swing.JComboBox<>();
        jBtnAgregarVehiculo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCboPartesExtra = new javax.swing.JComboBox<>();
        jBtnAgregarParte = new javax.swing.JButton();
        jBtnLimpiarSelecciones = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaVAgregados = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxaPAgregados = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxaFactura = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jCheckContado = new javax.swing.JCheckBox();
        jCheckCredito = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        jBtnAgregarCliente = new javax.swing.JButton();
        jBtnRealizarFactura = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioColones = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClienteActivo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jCheckColones = new javax.swing.JCheckBox();
        jCheckDolares = new javax.swing.JCheckBox();
        txtPrecioDolares = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro.png"))); // NOI18N
        jLabel8.setText("Seleccione El Vehiculo Que Desea");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar El Tipo De Vehiculo Deseado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("8-bit Operator+", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        buttonGroup1.add(jCheckFosil);
        jCheckFosil.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckFosil.setText("Fosil");
        jCheckFosil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckFosil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckFosilActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckElectrico);
        jCheckElectrico.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckElectrico.setText("Electrico");
        jCheckElectrico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckElectricoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckHibrido);
        jCheckHibrido.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckHibrido.setText("Hibrido");
        jCheckHibrido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckHibrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckHibridoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckTodos);
        jCheckTodos.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckTodos.setText("Todos");
        jCheckTodos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckHibrido)
                    .addComponent(jCheckTodos)
                    .addComponent(jCheckFosil)
                    .addComponent(jCheckElectrico))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckFosil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckElectrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckHibrido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckTodos)
                .addGap(16, 16, 16))
        );

        jCboVehiculos.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCboVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVehiculosActionPerformed(evt);
            }
        });

        jBtnAgregarVehiculo.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnAgregarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnAgregarVehiculo.setText("Agregar");
        jBtnAgregarVehiculo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAgregarVehiculo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarVehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgregarVehiculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mechanicwrench_118392.png"))); // NOI18N
        jLabel3.setText("Partes Extras Disponibles");

        jCboPartesExtra.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCboPartesExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboPartesExtraActionPerformed(evt);
            }
        });

        jBtnAgregarParte.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnAgregarParte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnAgregarParte.setText("Agregar");
        jBtnAgregarParte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAgregarParte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarParteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregarParte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboPartesExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jCboPartesExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAgregarParte)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 810, 190));

        jBtnLimpiarSelecciones.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnLimpiarSelecciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basurero.png"))); // NOI18N
        jBtnLimpiarSelecciones.setText("Limpiar selecciones");
        jBtnLimpiarSelecciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLimpiarSelecciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLimpiarSelecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarSeleccionesActionPerformed(evt);
            }
        });
        add(jBtnLimpiarSelecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, 200, -1));

        jTxaVAgregados.setColumns(20);
        jTxaVAgregados.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jTxaVAgregados.setRows(5);
        jScrollPane1.setViewportView(jTxaVAgregados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 600, 70));

        jLabel4.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mechanicwrench_118392.png"))); // NOI18N
        jLabel4.setText("Partes Agregadas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 290, -1));

        jTxaPAgregados.setColumns(20);
        jTxaPAgregados.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jTxaPAgregados.setRows(5);
        jScrollPane2.setViewportView(jTxaPAgregados);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 600, 120));

        jLabel9.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro.png"))); // NOI18N
        jLabel9.setText("Vehiculos Agregado");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 320, -1));

        jBtnSalir.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 820, 170, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        jLabel5.setText("Factura");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, -1));

        jTxaFactura.setColumns(20);
        jTxaFactura.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jTxaFactura.setRows(5);
        jScrollPane3.setViewportView(jTxaFactura);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 970, 550));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("8-bit Operator+", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        buttonGroup2.add(jCheckContado);
        jCheckContado.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckContado.setText("Contado");
        jCheckContado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckContadoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jCheckCredito);
        jCheckCredito.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckCredito.setText("Credito");
        jCheckCredito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckContado)
                    .addComponent(jCheckCredito))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckContado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckCredito)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 160, 100));

        jLabel6.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jLabel6.setText("Cliente Activo");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 290, -1));

        txtCedulaCliente.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaClienteActionPerformed(evt);
            }
        });
        txtCedulaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaClienteKeyTyped(evt);
            }
        });
        jPanel4.add(txtCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 230, 30));

        jBtnAgregarCliente.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnAgregarCliente.setText("Agregar Cliente");
        jBtnAgregarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnAgregarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 60));

        jBtnRealizarFactura.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jBtnRealizarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnRealizarFactura.setText("Realizar Factura");
        jBtnRealizarFactura.setEnabled(false);
        jBtnRealizarFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnRealizarFactura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnRealizarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRealizarFacturaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnRealizarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 210, 60));

        jLabel2.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colones.png"))); // NOI18N
        jLabel2.setText("Colones");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 193, 30));

        txtPrecioColones.setEditable(false);
        txtPrecioColones.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtPrecioColones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioColonesActionPerformed(evt);
            }
        });
        txtPrecioColones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioColonesKeyTyped(evt);
            }
        });
        jPanel4.add(txtPrecioColones, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 260, 30));

        jLabel7.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        jLabel7.setText("Cliente");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 290, -1));

        txtClienteActivo.setEditable(false);
        txtClienteActivo.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtClienteActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActivoActionPerformed(evt);
            }
        });
        txtClienteActivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteActivoKeyTyped(evt);
            }
        });
        jPanel4.add(txtClienteActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 290, 30));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo Moneda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("8-bit Operator+", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        buttonGroup3.add(jCheckColones);
        jCheckColones.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckColones.setText("Colones");
        jCheckColones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckColones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckColonesActionPerformed(evt);
            }
        });

        buttonGroup3.add(jCheckDolares);
        jCheckDolares.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckDolares.setText("Dolares");
        jCheckDolares.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckDolaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckColones)
                    .addComponent(jCheckDolares))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckColones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckDolares)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 160, 100));

        txtPrecioDolares.setEditable(false);
        txtPrecioDolares.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtPrecioDolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioDolaresActionPerformed(evt);
            }
        });
        txtPrecioDolares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioDolaresKeyTyped(evt);
            }
        });
        jPanel4.add(txtPrecioDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 260, 30));

        jLabel10.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio.png"))); // NOI18N
        jLabel10.setText("Precio");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 193, 40));

        jLabel11.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dolar.png"))); // NOI18N
        jLabel11.setText("Dolares");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 193, 40));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 970, 760));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarVehiculoActionPerformed
        // TODO add your handling code here:

        Vehiculo vehiculo;
        if (jCboVehiculos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el Vehiculo primero");
            getToolkit().beep();
            return;
        }
        vehiculoSeleccionado = (Vehiculo) jCboVehiculos.getSelectedItem();
        jTxaVAgregados.append(vehiculoSeleccionado.toString());
        jBtnAgregarVehiculo.setEnabled(false);
    }//GEN-LAST:event_jBtnAgregarVehiculoActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jCheckHibridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckHibridoActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculosFiltro();
    }//GEN-LAST:event_jCheckHibridoActionPerformed

    private void jCheckElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckElectricoActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculosFiltro();
    }//GEN-LAST:event_jCheckElectricoActionPerformed

    private void txtCedulaClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaClienteKeyTyped

    }//GEN-LAST:event_txtCedulaClienteKeyTyped

    private void txtCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaClienteActionPerformed

    private void jCboPartesExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboPartesExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboPartesExtraActionPerformed

    private void jBtnAgregarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarParteActionPerformed
        // TODO add your handling code here:
        if (jCboVehiculos.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe Agregar el Vehiculo primero");
            getToolkit().beep();
            return;
        }
        if (jCboPartesExtra.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la parte primero");
            getToolkit().beep();
            return;
        }
        parteSeleccionada = (Partes) jCboPartesExtra.getSelectedItem();
        listaPartesSeleccionadas.add(parteSeleccionada);
        jTxaPAgregados.setText("");
        for (Partes partes : listaPartesSeleccionadas) {
            jTxaPAgregados.append("\n" + partes.toString());
        }
    }//GEN-LAST:event_jBtnAgregarParteActionPerformed

    private void jCheckTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTodosActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculos();
    }//GEN-LAST:event_jCheckTodosActionPerformed

    private void jCheckFosilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckFosilActionPerformed
        // TODO add your handling code here:
        llenarComboVehiculosFiltro();
    }//GEN-LAST:event_jCheckFosilActionPerformed

    private void jCboVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVehiculosActionPerformed

    private void jBtnLimpiarSeleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarSeleccionesActionPerformed
        // TODO add your handling code here:
        vehiculoSeleccionado = null;
        parteSeleccionada = null;
        jTxaPAgregados.setText("");
        jTxaVAgregados.setText("");
        buttonGroup1.clearSelection();
        jCboPartesExtra.setSelectedIndex(-1);
        jCboVehiculos.setSelectedIndex(-1);
        listaPartesSeleccionadas = new ArrayList<>();
        jBtnAgregarVehiculo.setEnabled(true);
    }//GEN-LAST:event_jBtnLimpiarSeleccionesActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        UtilitarioVentana.cerrarPanel(this);

    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jCheckContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckContadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckContadoActionPerformed

    private void jCheckCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckCreditoActionPerformed

    private void txtPrecioColonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioColonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioColonesActionPerformed

    private void txtPrecioColonesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioColonesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioColonesKeyTyped

    private void jBtnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarClienteActionPerformed
        try {
            // TODO add your handling code here:
            ArrayList<Usuario_Cliente> listaClientes = Usuario_Cliente.listadoUsuario_Clientes();
            for (Usuario_Cliente cliente : listaClientes) {
                if (txtCedulaCliente.getText().equals(cliente.getIdentificacion())) {
                    usuario_Cliente = cliente;
                    txtClienteActivo.setText(usuario_Cliente.getUsuario().getNombre());
                    JOptionPane.showMessageDialog(this, "Cliente agregado, listo para facturar");
                }
            }
            if (usuario_Cliente == null) {
                JOptionPane.showMessageDialog(this, "El cliente no existe");
                getToolkit().beep();
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(jPanFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBtnAgregarClienteActionPerformed

    private void jBtnRealizarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRealizarFacturaActionPerformed
        // TODO add your handling code here:
        int cantidadPiezas = listaPartesSeleccionadas.size() + 1;
        double descuentoPiezas = 0;
        double descuentoTipoVehiculo = 0;
        double descuentoTipoFactura = 0;
        double IVA = 0.13;
        double descuento = 0;
        double subTotal = 0;
        double total = 0;
        double impuesto = 0;
        if (usuario_Cliente == null) {
            JOptionPane.showMessageDialog(this, "Debe agregar el usuario que desea facturar");
            getToolkit().beep();
            return;
        }

        // se le da los valores a las variables de descuentos tomando en cuenta las condiciones de cada una
        if (usuario_Cliente instanceof ClienteCoorporativo) {
            if (cantidadPiezas > 3 && cantidadPiezas < 5) {
                descuentoPiezas = 0.1;
            }
            if (cantidadPiezas > 5 && cantidadPiezas < 10) {
                descuentoPiezas = 0.2;
            }
            if (cantidadPiezas > 10) {
                descuentoPiezas = 0.25;
            }
        }
        if (usuario_Cliente instanceof ClientePersonal) {
            if (cantidadPiezas > 10) {
                descuentoPiezas = 0.15;
            }
        }

        if (vehiculoSeleccionado.geteTipoVehiculo().equals(ETipoVehiculo.ELECTRICO)) {
            descuentoTipoVehiculo = 0.05;

        }
        if (vehiculoSeleccionado.geteTipoVehiculo().equals(ETipoVehiculo.HIBRIDO)) {
            descuentoTipoVehiculo = 0.03;

        }

        if (jCheckContado.isSelected()) {
            descuentoTipoFactura = 0.05;
        }

        //se realizan los calculos
        subTotal = calculaSubTotal();

        impuesto = subTotal + (subTotal * IVA);

        descuento = subTotal - ((subTotal * descuentoPiezas) + (subTotal * descuentoTipoFactura) + (subTotal * descuentoTipoVehiculo));

        total = subTotal - descuento + impuesto;
        
        txtPrecioDolares.setText(String.valueOf(total));
        txtPrecioColones.setText(String.valueOf(total*630));
        
        try {
            numeroFacturaA = Factura.listadoFacturas().size()+1;
        } catch (Exception ex) {
            Logger.getLogger(jPanFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        factura = new Factura(numeroFacturaA,usuario_Cliente, descuento, subTotal, total, impuesto, vehiculoSeleccionado,listaPartesSeleccionadas);

        try {
            if (factura != null) {
                Factura.agregarFactura(factura);
            }
        } catch (Exception ex) {
            Logger.getLogger(jPanFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTxaFactura.setText(factura.toString());
        
    }//GEN-LAST:event_jBtnRealizarFacturaActionPerformed

    private void txtClienteActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActivoActionPerformed

    private void txtClienteActivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteActivoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActivoKeyTyped

    private void jCheckColonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckColonesActionPerformed
        // TODO add your handling code here:
         if (!jCheckContado.isSelected()&&!jCheckCredito.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe selecionar el tipo de factura primero");
            getToolkit().beep();
            return;
        }
        
        jBtnRealizarFactura.setEnabled(true);
    }//GEN-LAST:event_jCheckColonesActionPerformed

    private void jCheckDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckDolaresActionPerformed
        // TODO add your handling code here:
        if (!jCheckContado.isSelected()&&!jCheckCredito.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe selecionar el tipo de factura primero");
            getToolkit().beep();
            return;
        }
        
        jBtnRealizarFactura.setEnabled(true);

    }//GEN-LAST:event_jCheckDolaresActionPerformed

    private void txtPrecioDolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioDolaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioDolaresActionPerformed

    private void txtPrecioDolaresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioDolaresKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioDolaresKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBtnAgregarCliente;
    private javax.swing.JButton jBtnAgregarParte;
    private javax.swing.JButton jBtnAgregarVehiculo;
    private javax.swing.JButton jBtnLimpiarSelecciones;
    private javax.swing.JButton jBtnRealizarFactura;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<Partes> jCboPartesExtra;
    private javax.swing.JComboBox<Vehiculo> jCboVehiculos;
    private javax.swing.JCheckBox jCheckColones;
    private javax.swing.JCheckBox jCheckContado;
    private javax.swing.JCheckBox jCheckCredito;
    private javax.swing.JCheckBox jCheckDolares;
    private javax.swing.JCheckBox jCheckElectrico;
    private javax.swing.JCheckBox jCheckFosil;
    private javax.swing.JCheckBox jCheckHibrido;
    private javax.swing.JCheckBox jCheckTodos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTxaFactura;
    private javax.swing.JTextArea jTxaPAgregados;
    private javax.swing.JTextArea jTxaVAgregados;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtClienteActivo;
    private javax.swing.JTextField txtPrecioColones;
    private javax.swing.JTextField txtPrecioDolares;
    // End of variables declaration//GEN-END:variables
}
