package CapaVista;

import CapaLogica.ClienteCoorporativo;
import CapaLogica.ClientePersonal;
import CapaLogica.Pais;
import CapaLogica.TipoUsuario;
import CapaLogica.Usuario;
import CapaLogica.Usuario_Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import utilitarios.UtilitarioVentana;
import utilitarios.ValidadorFormatos;

public class jPanCrearCuenta extends javax.swing.JPanel {

//    private UsuarioBLL oUsuarioBLL = new UsuarioBLL();
    private static ClienteCoorporativo clienteCoorporativo = null;
    private static ClientePersonal clientePersonal = null;

    /**
     * Creates new form jPanCuenta
     */
    public jPanCrearCuenta() {
        initComponents();
        llenarComboPais();

    }

    //metodo para llenar el combo box Pais
    public void llenarComboPais() {
        jCboPais.removeAllItems();
        for (Pais pais : Pais.values()) {
            jCboPais.addItem(pais);
        }
        jCboPais.setSelectedIndex(-1);
    }
    
    //metodo para limpiar los campos
    public void limpiarCampos() {
        txtCedula.setText("");
        txtCorreoElectronico.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtNombre.setText("");
        jCboPais.setSelectedIndex(-1);
        JPassContrasena.setText("");
        JPassConfirmacionContrasena.setText("");
        jCheckCorporativo.setSelected(false);
        jCheckPersonal.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCboPais = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JPassContrasena = new javax.swing.JPasswordField();
        jBtnCrear = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JPassConfirmacionContrasena = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jCheckCorporativo = new javax.swing.JCheckBox();
        jCheckPersonal = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("8-bit Operator+", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 94, -1));

        txtNombre.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 320, 30));

        jLabel2.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Email.png"))); // NOI18N
        jLabel2.setText("Correo Electronico");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 193, 30));

        jCboPais.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCboPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboPaisActionPerformed(evt);
            }
        });
        add(jCboPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 320, 30));

        jLabel3.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pais.png"))); // NOI18N
        jLabel3.setText("Pais");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 185, 30));

        txtCorreoElectronico.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoActionPerformed(evt);
            }
        });
        txtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoElectronicoKeyTyped(evt);
            }
        });
        add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 320, 30));

        jLabel4.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PasswordIcon.png"))); // NOI18N
        jLabel4.setText("Contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 185, 30));

        JPassContrasena.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        JPassContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPassContrasenaActionPerformed(evt);
            }
        });
        JPassContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JPassContrasenaKeyTyped(evt);
            }
        });
        add(JPassContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 320, 30));

        jBtnCrear.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jBtnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CheckNegro.png"))); // NOI18N
        jBtnCrear.setText("  Crear ");
        jBtnCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCrearActionPerformed(evt);
            }
        });
        add(jBtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        jBtnSalir.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida.png"))); // NOI18N
        jBtnSalir.setText("  Salir ");
        jBtnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PasswordIcon.png"))); // NOI18N
        jLabel5.setText("Confirmación");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 185, 30));

        JPassConfirmacionContrasena.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        JPassConfirmacionContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPassConfirmacionContrasenaActionPerformed(evt);
            }
        });
        JPassConfirmacionContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JPassConfirmacionContrasenaKeyTyped(evt);
            }
        });
        add(JPassConfirmacionContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 320, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo De Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("8-bit Operator+", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        buttonGroup1.add(jCheckCorporativo);
        jCheckCorporativo.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckCorporativo.setText("Corporativo");
        jCheckCorporativo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(jCheckPersonal);
        jCheckPersonal.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        jCheckPersonal.setText("Personal");
        jCheckPersonal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckCorporativo)
                    .addComponent(jCheckPersonal))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jCheckCorporativo)
                .addGap(18, 18, 18)
                .addComponent(jCheckPersonal)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/direccionm.png"))); // NOI18N
        jLabel7.setText("Dirección");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txtDireccion.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 320, 30));

        jLabel8.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel8.setText("Cédula");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 94, -1));

        txtCedula.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 320, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioB.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("8-bit Operator+", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telefono.png"))); // NOI18N
        jLabel10.setText("Teléfono");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 180, 37));

        txtTelefono.setFont(new java.awt.Font("8-bit Operator+", 0, 12)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 320, 30));
    }// </editor-fold>//GEN-END:initComponents

    //boton para salir del panel
    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        utilitarios.UtilitarioVentana.cerrarPanel(this);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCrearActionPerformed
        String contrasenaUsuario = "";
        // validaciones para los campos de texto
        if (ValidadorFormatos.validarVacio(txtNombre.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar su nombre");
            txtNombre.requestFocus();
            return;
        }
        
        try {
            ArrayList<Usuario_Cliente> lista = Usuario_Cliente.listadoUsuario_Clientes();
            for (Usuario_Cliente usuario : lista) {
                if (txtCedula.getText().equalsIgnoreCase(usuario.getIdentificacion())) {
                    JOptionPane.showMessageDialog(this, "Esta Cedula ya existe");
                    return;
                }
            }
        } catch (Exception ex) {
            
        }
        
        if (ValidadorFormatos.validarVacio(txtCedula.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar su cedula");
            txtCedula.requestFocus();
            return;
        }
        if (ValidadorFormatos.validarVacio(txtDireccion.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar su direccion");
            txtDireccion.requestFocus();
            return;
        }
        if (ValidadorFormatos.validarVacio(txtTelefono.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar su telefono");
            txtTelefono.requestFocus();
            return;
        }

        // validar que sean letras 
        // valida que el campo del correo electronico no este vacio
        if (ValidadorFormatos.validarVacio(txtCorreoElectronico.getText())) {
            JOptionPane.showMessageDialog(this, "Debe digitar su correo electronico");           
            txtCorreoElectronico.requestFocus();
            return;
        }
        //valida que la contraseña sea mayor a 0 y menor a 12
        if (String.valueOf(JPassConfirmacionContrasena.getPassword()).length() >= 0 && String.valueOf(JPassConfirmacionContrasena.getPassword()).length() <= 12) {
            contrasenaUsuario = String.valueOf(JPassConfirmacionContrasena.getPassword());
        }

        // validar que el combo box no esté vacio
        if (jCboPais.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el país");
            jCboPais.requestFocus();
            return;
        }

        // validar que el passfiel de contraseña no este vacio
        if (ValidadorFormatos.validarVacio(String.valueOf(JPassContrasena.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la contraseña");
            JPassContrasena.requestFocus();
            return;
        }

        //Validar que el passfiel de confirmacion contraseña no este vacio
        if (ValidadorFormatos.validarVacio(String.valueOf(JPassConfirmacionContrasena.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Debe confirmar su contraseña");
            JPassConfirmacionContrasena.requestFocus();
            return;
        }

        if (String.valueOf(JPassContrasena.getPassword()).equalsIgnoreCase(String.valueOf(JPassConfirmacionContrasena.getPassword()))) {
            
          
        } else {
            JOptionPane.showMessageDialog(this, "La contraseña debe coincidir");
            return;
        }

        // validar correo con @ y .com y (gmail||hotmail)
        if (txtCorreoElectronico.getText().contains("@") && txtCorreoElectronico.getText().contains(".com")) {
            if (txtCorreoElectronico.getText().contains("gmail") || txtCorreoElectronico.getText().contains("hotmail")) {
                
            }
        } else {
            JOptionPane.showMessageDialog(this, "Su correo no es válido");
            txtCorreoElectronico.requestFocus();
            txtCorreoElectronico.selectAll();
        }

        //validar que JPassContrasena este entre 8 a 12 caracteres
        if (String.valueOf(JPassContrasena.getPassword()).length() >= 8 && String.valueOf(JPassContrasena.getPassword()).length() <= 12) {
            
        } else {
            JOptionPane.showMessageDialog(this, "La contraseña debe contener entre 8 a 12 caracteres");
            JPassContrasena.selectAll();
            JPassContrasena.requestFocus();
            return;
        }

        //validar que JPassConfirmacionContrasena este entre 8 a 12 caracteres
        if (String.valueOf(JPassConfirmacionContrasena.getPassword()).length() >= 8 && String.valueOf(JPassConfirmacionContrasena.getPassword()).length() <= 12) {
            
        } else {
            JOptionPane.showMessageDialog(this, "La contraseña debe contener entre 8 a 12 caracteres");
            JPassConfirmacionContrasena.selectAll();
            JPassConfirmacionContrasena.requestFocus();
            return;
        }

        //variables validadoras para la clave (deben de estar las 3 en True para que sea correcta)
        boolean validador1 = false;
        boolean validador2 = false;
        boolean validador3 = false;

        //validacion de minusculas, mayusculas y digitos
        for (int i = 0; i < contrasenaUsuario.length(); i++) {
            char a = contrasenaUsuario.charAt(i);
            if (Character.isLowerCase(a)) {
                validador1 = true;
            }
            if (Character.isUpperCase(a)) {
                validador2 = true;
            }
            if (Character.isDigit(a)) {
                validador3 = true;
            }
        }
        //validar que los validadores de caracteres sean Verdaderos los 3
        if (!(validador1 == true && validador2 == true && validador3 == true)) {
            JOptionPane.showMessageDialog(this, "La clave debe contener almenos una letra Mayuscula, una Minuscula y un Numero");
            JPassContrasena.requestFocus();
            JPassContrasena.setText("");
            JPassConfirmacionContrasena.setText("");
            getToolkit().beep();
            return;
        }

        //validar que se seleccione 1 de los jCheckBox
        if (!jCheckPersonal.isSelected() && !jCheckCorporativo.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo cliente");
            jCheckCorporativo.requestFocus();
            getToolkit().beep();
            return;
        }

        if (jCheckCorporativo.isSelected()) {
            //creacion de cliente coorporativo

            Pais paisSeleccionado = (Pais) jCboPais.getSelectedItem();

            Usuario usuarioCoorporativo = new Usuario(txtCorreoElectronico.getText(), contrasenaUsuario, txtNombre.getText(), paisSeleccionado, 
                    txtDireccion.getText(), txtTelefono.getText(), TipoUsuario.USUARIO_REGULAR);
            clienteCoorporativo = new ClienteCoorporativo(usuarioCoorporativo, txtCedula.getText());
            if (clienteCoorporativo != null) { //Revisa si el JDialog construyó el nuevo 
                try {
                    Usuario_Cliente.agregarUsuario_Cliente(clienteCoorporativo);
                    JOptionPane.showMessageDialog(this, "Creado con exito");
                    UtilitarioVentana.cerrarPanel(this);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el usuario\n"
                            + "el programa se cerrará consulte con el administrador\n"
                            + e.toString());
                    System.exit(0);
                }
            

            }
        }
        if (jCheckPersonal.isSelected()) {
            //creacion de cliente personal
            Pais paisSeleccionado = (Pais) jCboPais.getSelectedItem();
            Usuario usuarioPersonal = new Usuario(txtCorreoElectronico.getText(), contrasenaUsuario, txtNombre.getText(), paisSeleccionado, 
                    txtDireccion.getText(), txtTelefono.getText(), TipoUsuario.USUARIO_REGULAR);
            clientePersonal = new ClientePersonal(usuarioPersonal, txtCedula.getText());
            if (clientePersonal != null) { //Revisa si el JDialog construyó el nuevo 
                try {
                    Usuario_Cliente.agregarUsuario_Cliente(clientePersonal);
                    JOptionPane.showMessageDialog(this, "Creado con exito");
                    UtilitarioVentana.cerrarPanel(this);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el usuario\n"
                            + "el programa se cerrará consulte con el administrador\n"
                            + e.toString());
                    System.exit(0);
                }
              

            }
        }

        limpiarCampos();
       

    }//GEN-LAST:event_jBtnCrearActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        txtCedula.requestFocus();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        //validar que el usuario este digitando solo letras
        if (Character.isDigit(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe digitar solo letras");
        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCorreoElectronicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoKeyTyped

    }//GEN-LAST:event_txtCorreoElectronicoKeyTyped

    private void JPassContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPassContrasenaKeyTyped
        //tope maximo de 12 carateres en la clave
        if (JPassContrasena.getText().length() >= 12) {
            getToolkit().beep();
            evt.consume();

        }

    }//GEN-LAST:event_JPassContrasenaKeyTyped

    private void JPassConfirmacionContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPassConfirmacionContrasenaKeyTyped
        //tope maximo de 12 carateres en la clave
        if (JPassConfirmacionContrasena.getText().length() >= 12) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_JPassConfirmacionContrasenaKeyTyped

    private void JPassContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPassContrasenaActionPerformed
        // TODO add your handling code here:
        JPassConfirmacionContrasena.requestFocus();

    }//GEN-LAST:event_JPassContrasenaActionPerformed

    private void jCboPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboPaisActionPerformed
        // TODO add your handling code here:
        JPassContrasena.requestFocus();
    }//GEN-LAST:event_jCboPaisActionPerformed

    private void JPassConfirmacionContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPassConfirmacionContrasenaActionPerformed
        // TODO add your handling code here:
        jBtnCrear.doClick();
    }//GEN-LAST:event_JPassConfirmacionContrasenaActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
        jCboPais.requestFocus();
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoActionPerformed
        // TODO add your handling code here:
        txtTelefono.requestFocus();
    }//GEN-LAST:event_txtCorreoElectronicoActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
        txtCorreoElectronico.requestFocus();
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        //valida que el usuario solo digite numeros
        if (Character.isLetter(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe digitar solo números la cedula");
        }

    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
        txtDireccion.requestFocus();
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        //valida que el usuario solo digite numeros
        if (Character.isLetter(evt.getKeyChar())) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debe digitar solo números en el telefono");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPassConfirmacionContrasena;
    private javax.swing.JPasswordField JPassContrasena;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCrear;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<Pais> jCboPais;
    private javax.swing.JCheckBox jCheckCorporativo;
    private javax.swing.JCheckBox jCheckPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
